name: Node Continous Integration
on: push
jobs: 
    build-job:
        name: Build Node Project
        runs-on: ubuntu-latest
        steps:            
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v2
            - run: node app.js
            - run: python3 --version
            - run: python3 main.py
            - run: pwd